version: "3"
services:
  mongodb:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
  mongo_seed:
    container_name: mongo_seed
    build:
      dockerfile: Dockerfile
      context: ./mongo_seed
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    env_file:
      - ".env"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - GENERATE_SOURCEMAP=false
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  mongodb_data_container:
