FROM mongo:latest

# COPY project_types.json /project_types.json
COPY init.js /init.js

# Add docker-compose-wait tool -------------------
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

CMD mongo --host mongodb issue-tracker init.js